spring.application.name=mantisbt-attachments
spring.datasource.url=jdbc:mysql://127.0.0.1:23376/plastimaxbt
spring.datasource.username=root
spring.datasource.password=DEVELOPMENT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
